@startuml
left to right direction

actor Visiteur

rectangle "SoliCode Blog" {
  Visiteur --> (Consulter la page d’accueil)
  Visiteur --> (Rechercher un article)
  Visiteur --> (Voir les articles récents)
}

@enduml
